---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-creds
  namespace: default
spec:
  encryptedData:
    password: AgB0KaE2EME92MbAogiU99asUQ2tfF0OyZDYn/04HoJGiSxIzFKp7RIKqU8oGLf7/VJ4gTzl3aFqYF0K/6fBbuslfGaBO1LohD0o0O4vsxzUWmhYcW8/8t8FB6LN5YH7VL1qKfcaC1ZAa3U/qnU+unapsLYuJai2mKrLyWFJ0bSPaWcCGlVDR4rjeoqSWdBe4QfHrYYbop6mXi/6yNHS6UMisq4eK7DEsSnQNj0BiNanNo7cKSrui/GB2MAQkwlRYwJ7rGEHUI7ArviY/7013PKYtc0eHXkYBLPLiDHevcFDGSYljLVOv7IRq722SbCLpYQCEmEgSj/ZuhGp2KHj77dyM97EsKjs3KCueVvYXsMQKXGRTvR4gS74A7PAPvr2UP03fmP9/v38Kc1mR2gshMJMiZuzn47Kok1dA1vtzgCThsT7BNPULWvmd/OGYTds/Y4doElBmMsQ15D9S9h0Rp5R6xGax7oKToR1CGnPFM2MHeGoAma9qfkV/In6ZtvadZsRC1RLZ6QaHnRxZhPIn1r3d1x5Y7e+cl+5YRDKvuM5FYjHFMlZ0NThUafLYjYUB8qAVFvXBFDr+x2qeXf1loH9RAiEcoXmcsjqr+q8NEa6oanz1MCYEaPPglzbmzE7pMZyAMiA7Ecsfbfw1h+MnjNG4SHT0qyxUQABFTfSi10cAAgFv6xKaWpPukiL7eewg6t+0pPUxQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-creds
      namespace: default
