apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: "25.2.0"
    helm:
      values: |
        global:
          imageRegistry: "public.ecr.aws"
          security:
            allowInsecureImages: true
        auth:
          adminUser: admin
          existingSecret: "keycloak-creds"
        production: true 
        proxy: edge
        ingress:
          enabled: false
        extraEnvVars:
          - name: KC_HOSTNAME_URL
            value: "https://auth.260824.xyz"
          - name: KC_HOSTNAME_ADMIN_URL
            value: "https://auth.260824.xyz"
          - name: KC_PROXY_HEADERS
            value: "xforwarded"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"
        postgresql:
          enabled: true
          auth:
            username: "keycloak"
            database: "keycloak_db"
            existingSecret: "keycloak-creds"
          primary:
            initdb:
              scripts:
                init_solar_tables.sql: |
                  CREATE TABLE IF NOT EXISTS companies (
                      id SERIAL PRIMARY KEY,
                      name VARCHAR(255) NOT NULL,
                      asset_ids TEXT[] DEFAULT '{}'
                  );
                  
                  CREATE TABLE IF NOT EXISTS users (
                      id VARCHAR(255) PRIMARY KEY,
                      company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
                      expo_push_token VARCHAR(255)
                  );
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true