apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: "*"
    # targetRevision: "25.2.0"
    helm:
      values: |
        auth:
          adminUser: admin
          existingSecret: "keycloak-creds"
        production: false 
        proxy: edge
        postgresql:
          enabled: true
          auth:
            username: "keycloak"
            database: "keycloak_db"
            existingSecret: "keycloak-creds"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true