apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - cloudflared.yml
  - github-runner.yml
  - infrastructure-runner.yml
  - keycloak.yml
  - loki.yml
  - mongodb.yml
  - ollama.yml
  - prometheus.yml
  - rabbitmq.yml
  - timescaledb.yml
  