apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "84.2.1"
    helm:
      values: |
        prometheus:
          prometheusSpec:
            scrapeInterval: "30s"
            retention: "48h"
        grafana:         
          admin:
            existingSecret: "grafana-creds"
            userKey: username
            passwordKey: password
          deploymentStrategy:
            type: Recreate
            rollingUpdate: null
        global:
          imagePullSecrets:
            - ghcr-secret
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true