---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: timescaledb-creds
  namespace: default
spec:
  encryptedData:
    password: AgBMixxunPvoBAYs1CzlZ3gdoVmZaFNKEql9eb5jcIntuICiEH2xtBezBLHt14fzo8ZnD9LnZmeRMJ1E7k3amLOWvy5bP0e7r88e2xLQSUGkvgFQWbUGOgtae7m88OXzguii2vNp++oua3/3/1gUY4tq0G24mOo3n6DaUIZzpJ0fjyUiRdFrbo1zBfm+MYruMI7XY1bH+gbMqrg3k1EgFnpL4E0GHpEMBGpF8ya0Lp5fsRT1V+EUNzX4Ds033j+20dWqvK8E8zUIqQXN9tcYg7101sZILqsQ7Wt1yaZzsZWKAHkJUfgUB1oBNX0FDCEOYYyyg7ZKm036bGsXC95BGmirkPXu7B8tydQ+wcICWkmi/1wormMqd8CPE0eu8CNwXupzIDtbnaE2Z6FBjg4p/P/5TbIKKwur5wG3W99u3QISN8bqn+GUHgTNLccWZikPEDWTBGMMiVe45dVpUGLBePU+hyyccxEc5HyRK9fGD3fji//LA8FCO5XGW5Cv9zRUgTAJBUP/shRxyakCL3pblTRVRvgjWuoY6scespcPLkrrosIa5vaLrXgiK+Aumzb/6/srtc6C71BKUwP+l38KOJM6xeOOMh4tDXgkYUE2/Md0u0NSyEEeCbqqM8LAsa/B7DR/V1nJkQP4Ml1ONawC2GUwUAvKByn6dauNNw71ZOvICwSkXq0fN0iLzzO/2O+siCY+GTtljw==
    username: AgBecRZk2XuKFN8F7CQiH04xae3e9UjLAiZlXGVlkmnFQGUSdYw54ctGM41FaRblbzrtBBXBFyP/Rs5Fn52/Z6EmyDqvf+pO/w1lVxwrqYVT8NfWAOAhlWYMIf4F4WHvWxE4E/pCDoxj2EbGJX3RaqCAfdSGQs8rJIpPyi8GpcvgkRo4MenZ0v3wwUSW+C4V+8K3S8/feltPKyTi4WldSGx069GRr0UwijuVB/WGtf2C50JZEHbMv/hwIZ8zrQtnE4ppobCtFufaMo7pgUKvPAzyxUiE2O7HWOy4DLgGKiJPEMEw9nj0lqyysizJLRdl8eFuQYv+/FAg/h1TpKiZNHcJtGyNDPMqzE6klN7JSIqxj/7MeC5R1DtZmc3kteBlhdh6Ib5Digxt2HoC8FMlzmLmj0j1V9XkGLWLNjE/A1UGmOPpvn/TZRL2cJ21B+fQqr4mSgOm4gSKIhzFWxEI0XvIuiJ0Yg4Sm23Ar+xZcqWa9on6usYIHzA6YgaLDBlWDW3V3WazBnxIYw1k1P/nzVuKf2TWstVuL14oZH4aV73dizpQfUQW4vvFHlO2Y7PqMtRdJ65T9ds8jmJcBwPu9ixfAww15yHr5KybMoP3cf8VGBmklxA/AYTOEi2fJM8pRd75xObFMJIA2hd4auLYoP/fL6NiEIjucnT+Onh4RvgZTcwypJPW9kBZs1lmHMXKrzNuoKU1Qw==
  template:
    metadata:
      creationTimestamp: null
      name: timescaledb-creds
      namespace: default
