---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: timescaledb-creds
  namespace: default
spec:
  encryptedData:
    password: AgB7+nd5KLXiZktiyoZa3Ou6RefkfXBBD4qig7S+wKU3t4jdvSSV3C+rQR8C0TfQyChi2ghl3bPNLi1xMfJlJ3sjviB9PhXTrcnm9nGGRA7EXLhXHzjaaPihIIr0zuSQKtIW2PNGaQRAr526im3fuC7Nsjg21V5D4aZP/EWjFnUD9sgNTI271EDcK/M/OUUU6ollaFR5HrC8Tdpmm6hC+H7PR2M9+BSn9tH8h4ogPhUuhqEzVjZYRtKfiXupNjnlld4240bnFEYyMN8jWvvz1W6Bt9uHJ2E23ODZef9+0L/LHvZgVC6p4eMjE09Rvyfd5KygqSRXhqWzB+9o2JXCwAmj/S/DxZkKJ3pSIsVgtK4Vb5D0F28dt//hcq1YgPQ6eplAl+rc6y+s9e4fPiMqhdXVoHdMwIAtKRewdK0zqtngXEpVJ8rC/HcOSEWCTkUCp9+GWovXLYVvDSCCCo8qQMfSNnRdVdbpwy2YjOHC2TbOyDzd8vEVkULFYAdOJMsyxo8GCZlUVnXlE8+7Kq7brzpVBZMpGimk3+y5G3cOzK7F9iONDUJ5bk3K2gQsZZvV4kAn0LnfDOkq0m4QNC61NMDCDyjrD7aOm3tBh1eha4kfw1Xpavzvwu4l1fbsg6toiMkQdziGOKkKrYi4Sg922Kp5hlYGoVI1Ynfj8uUTXToGUFUrfn6t0I1rIkfQK/xKoRrnRkY9wA==
    username: AgAsAspBjMvWoz4JtLrBZ11oVCcAqBn/8yvwvok73/61gPK/OfDazHxBR5FlNcs3lC0ss+rCKsAWCc33KMPzZUMKuKMTuigMgLGKUf2KoIQoe5rSh2Z6VnfMGSveORvhkt4nC2WEVjvmQgjZFRG0m6AuDF36xj/xavEaIU0HWdOHfTJkU84o0OUNX94uH89haKh/lbneUVv3ih88Un18Ad8CnekVva14N0tJ2K5isvZlry/frStTH7noOhXRamT9AeTH/MMY3OXLJ+randE741GRSJ9o47UINDll53pMJxMzdHKN16tPvfsJphSnKbW54M2MMwrkbAnXsbZLgsa+LwBAno/U5JIPt4Hq+CJjD3mn4YRSx6sSAycktw32Xf3HF1btm9Hu6kglZy1KzGOxxaJd7OiJGNDmxwyF7D4amL6Ma9EEjZ/sVPwXSvLvIfT2ERR0jzckTNrc6KRtvSW03RjlizUck1QTkcpbXQ8Bq19lFBVE6LLNP2xeg4pTKY74KxknKQzPYEcUBHX9qVZn6Ss7JS7yH0bzhK36tDstsr7itXNcHafSZbm/KPh63XymbWaR1CVD2te7q58PKYMAxQCc7xSUCb9dFSUW5XitKCYPFWzILBaeCEudcaRNEOLJf97gHjZM4rWUTUtuRu8v9XefFMKpmtuRvuf0FDDUh6uGbxzUWrhmkD2Cy7moS48cUsgR9yRVLw==
  template:
    metadata:
      creationTimestamp: null
      name: timescaledb-creds
      namespace: default
