apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp32-simulator
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: esp32-simulator
  template:
    metadata:
      labels:
        app: esp32-simulator
    spec:
      enableServiceLinks: false
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: esp32-simulator
        image: esp32-simulator
        imagePullPolicy: Always
        env:
        - name: DEVICE_ID
          value: "ESP_test"
        - name: MQTT_BROKER
          value: "rabbitmq"
        - name: MQTT_PORT
          value: "1883"
        - name: SEND_INTERVAL
          value: "30"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: timescaledb-creds
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-creds
              key: password