---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: expo-app-creds
  namespace: default
spec:
  encryptedData:
    expo-push-token: AgCRxEZMwFD/oTI/jh94bVSvWrPxQVyFsfn38tB6R7h06fN7vaQUdWz2ncT10lfOMQXGqUHG3XU8HvncegPuNbtdsvknn/oC9p0S1KrnbcdTZJao+oo2EGDH1OEDvowEMchOi1r8ZAr8aAA+rxrz346omtSjcVpGB8BnT3nFrui0jS6rP+mq5kcdaa3hDMzFZCnUmmnuM0E73omlDxwkCOoLjoAarc22+lvEP9UXqp3ppZBVY1/rFTaKYuWdMF8hjA4nXsoqFkcXSOmrw6NRceKYBNcTc9fc8EBQUKujia65gsXPsAV16qK6M5dBwELxdS9EioS1PVmtF4u1y+lVGEotECkOTXMvLhxeboKgLxX+JX0iHEcOratac1kCUSmoP8cdBfFOj0Dn/K6ToDQnC0PXLv4jASH8TKDnEhG/mEyD3+dWizx8N8IFevkWeX9GQXujJI03tSuYdI7lB9eoM2fsQJVeL6H9EUSE0kxUoj9JtS/hjldPCSTHGHnuJsasqxDhf3R00Z91nQ5XOMTwMZwTYv45taTWbSj2G17RN2jDFgx8GlsTQxDmpebF3jYz7BLlgLWv6dKXE3IIDhIoUJodbwo/ojZWF8t8+LTpJh2d7mVg6V0gwM6fFSOIehwkOOt/ZSACT3yOxlOe73XRB3lsnTLkVKuHDlxslNk+rBaDKGie0ijD0TVk5ySOaBYgwwa7E3NWIhKP6BJlstetHISOIynbTCjUX1RicwUGvnlnyGxRSSqygPqxqA==
  template:
    metadata:
      creationTimestamp: null
      name: expo-app-creds
      namespace: default
