apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: myoung34/github-runner:ubuntu-jammy
        env:
        - name: OLLAMA_URL
          value: "http://ollama-service.ai-agent.svc.cluster.local:11434"
        - name: MODEL
          value: "qwen2.5:0.5b"
        - name: IGNORE_EXTENSIONS
          value: ".png,.jpg,.jpeg,.lock,.pyc,.exe,.toml,.json,.txt"
        - name: IGNORE_FILES
          value: "Dockerfile,.gitignore,secret.yml,install.yaml,ghcr-secret.yml,TODO.md"
        - name: ROOT_DIR
          value: "."
        - name: REPO_URL
          value: "https://github.com/klaudiuszsoltysik/solartracker"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: ai-agent-creds
              key: github-token
        - name: RUNNER_LABELS
          value: "k8s-ai-agent"
        - name: RUNNER_WORKDIR
          value: "/tmp/runner"
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock