---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-agent-creds
  namespace: ai-agent
spec:
  encryptedData:
    github-token: AgAY+xZL69aEelE2PcSXrpM+9x/QTn6SVuIZ+OFy2LyplS6ZcKj15AjtPI3uyqNlVVm4G+aWYdcAi9l7SbgCtWhXdRXaWTbBnTH06Pff11aZL49bB7HxUs7SjtJKmvbkBcs9kJqKW7Ua+LygHGBe6iA+4+pbLsVPlw9I7Nkb+YrOUyPO/U9yfPD44JxuQMzvLpwbNxOuAm5uaIY9O/Y8f6UAcDuuwTM2VutfpEFSVjiQm0JzXEVVLRb44XajXz+4zqcSLYVTdCEAM8BCfyCUxJihTKCB2tSeWgcu0+j+Rwp+ymj45yK1BoKsPjy/9PBv/zxjen/ZRhvPWYup777MwBhMoZpHuNcGZPWVb9dO3wsqKoNHuel4BOXnqyDHtJ+nJNOts03Oe0lByHhMysGJG8XXgNkMqx9UKnAib/RTR6aSuseOnUUAye997DhuEy0UgcL/l+2xWkVEuUyoeHYwlWbOFp1lISEqp1nmhQLN5n3gAIqHEq33hgAdJkUgANlULjba0jV4lrGaz9mk267KjGRyHmuhPgnfezk3upFSgINfNkcjSlPZwI1vRhx4Dzzlqu1GRmRKs1tM5qYgFSyOM1EHmMReZ8k4G+u+uUAEjn6ZHvU2TpuVrqJP5jmbXmrJuNfU5wWzBpWREne5KtQSjgUdYAVgCApyycARAGfu+qPU319PuzJ4misf75Z+89IqIYp4JfhePEQdDxcvTBzY4xh/5qkj2IKRLpmwFdhljHgkrUybpT7h26Se
  template:
    metadata:
      creationTimestamp: null
      name: ai-agent-creds
      namespace: ai-agent
