apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-runner
  namespace: infrastructure
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: infrastructure-runner
  template:
    metadata:
      labels:
        app: infrastructure-runner
    spec:
      serviceAccountName: infra-runner-sa
      containers:
      - name: runner
        image: myoung34/github-runner:ubuntu-jammy
        env:
        - name: REPO_URL
          value: "https://github.com/klaudiuszsoltysik/solartracker"
        - name: RUNNER_NAME
          value: "infrastructure-runner"
        - name: RUNNER_LABELS
          value: "k8s-infra-runner"
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-creds
              key: github-token
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock