---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-runner-creds
  namespace: infrastructure
spec:
  encryptedData:
    github-token: AgBq4RHM54lbEQsXdfZSivJKMJuFDenOzLFSm0FA8cl7r984noV7NJ2lxAncC3nfdsZxnk34Nro83+BmcCP5XnbOTVhrXy0TuAWqzi0yyg7JB7nUUp869q0/V5dTIoEZrAFXHSrxuWR9/CwuTMpFtqNxgdkLEM2YfLhEwb06tt4Op9FxFMzTf61rs6h4f+xpxjYjNB3A5JGYG9oPKM2MBzwgg9LhazAwrg38JVnOR8kY+ib0m0fxlb23rygrqwRL7t9P36O0zSZ66lYw5qkDJlagv6KuaZf0DdJnD0Ebn7nvRdV2JnfkpFMJanVBoSIpRoXYn3nGLm3HqZgguVL+6l8Leil95OARX/3PKIufTLU6li3Q0JuB9cthgqnaqFj3woFOoitdQY2Hr3dt14mDQJEq8k3DYb+vJitpV1eTbj7Z8YZI/glP9ZaBZI3+4YgT8WbHqxIKMWTf8FCbNrBugahXApHo1w30K4aOdlmwfzone/4kqwJz1pMuMu2fwLsopPFauI798TIvjSO3SJqnUE0kN2HQK9D/b2vohA2sk7hhh5hmOorxifj2UMEoTuSUJJbrB066pytk1YhvaKpsQQjT6ahZez/qLc/xJ8kzvtW1Fh6c+J16nIuwR85cWAb09vsERG2eq2VWNiCOET8G2ZBwyoN1i5ZyE/7SWp24OQHiT44FTcL567myVqLML4Ormw8A9tmqQLbTdZvYouFxA/T20EE44RvsAOa1QzGlU7LXthQHbqPjzJAs
  template:
    metadata:
      creationTimestamp: null
      name: github-runner-creds
      namespace: infrastructure
