---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBwqlSJKUy2uYNgNm/g/VDCCMrxpqQ9ZTVVRqfdh60yPu5bcBDIiawKDOHpAx+3cTVUgCnnbuilAf2rpidhMMxj9qO/FyrQ1kYj9g4y5XIdSaCwd45HLUjARfVDnmjaTiJLrc20aPdLtoBgZ1o0EG3cVRhRgpta+XU8bMkFgfT6/Be1L96fkYGkJvbeAOrKFlZQtwX5abNtHHQP+D9k61SgTPy6nC3rHKj1v7sD/lEBBGGEeZIhnW6k1QIlQMxOWCgN9eZTBdOlGP7puwFvbSk60zG5qfk35id2UtDVVbdJbv+CvuKaD7d4IxqgFIXmcZG7bO6xa/FTM3jURVohHK4Y21WP80mqYgV4SIWiBoZjA41HwbaPMKiyAuPPnEFaBi6azQa7/itRO2PatlZJkFZ1Ln/e0AlIfCZIx50pbXeQrshz8WT25UfMclqmAdxj4XHtgNr1z6FO8HrYw0oTJr8NuGjr/NUm/FM4CDfPcLvSLgu2XjVvR2jqqw4+EDzATmWPV86WPqu3Ft1kj9DNLd5w6N+9qK6rQqEpIGfbh19+rPXMBZL7GhtHiEccKPjNlCGZJNfw18tcOzAUOjwHJLYhr4higoV4s9f2/j1OXz8eknj05jVWwMUvu7b56morSW5LU8lOa7zFOEVbyg5R5XHvxe3/vrgGXiBQhwKD/YGo+FJTEKG6g5E0WamfllvdTrYSgvwiowxdxZ3IAXL763j3X+jXULPOQAdklx5PWNTgxqWG071/yi5qA5Z4ZZhR1QmAVy64PlHaCBlMWbZ2zhiJsr8pwkT3sHBWFLgDKYIeNq08d4bk0nRSPkimaOua13NJ7uGyC6anexvPPm+g79IZSXSm03uM29gJkXnQgA7B7cnOnRMCbEQZrRfiM5+iCsmuOvPKPN/uY9aAhFbFb33K6OVzQ5ox5Qokd06r+Tv2yLAu+rNVpGUsXWTTQFmMPvLCR4+Cc06i5LfT3XH7vrM22kZUpJrbqUKPla764LfI7ud7LKj1zIkb0f8=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: observability
spec:
  encryptedData:
    .dockerconfigjson: AgBwqlSJKUy2uYNgNm/g/VDCCMrxpqQ9ZTVVRqfdh60yPu5bcBDIiawKDOHpAx+3cTVUgCnnbuilAf2rpidhMMxj9qO/FyrQ1kYj9g4y5XIdSaCwd45HLUjARfVDnmjaTiJLrc20aPdLtoBgZ1o0EG3cVRhRgpta+XU8bMkFgfT6/Be1L96fkYGkJvbeAOrKFlZQtwX5abNtHHQP+D9k61SgTPy6nC3rHKj1v7sD/lEBBGGEeZIhnW6k1QIlQMxOWCgN9eZTBdOlGP7puwFvbSk60zG5qfk35id2UtDVVbdJbv+CvuKaD7d4IxqgFIXmcZG7bO6xa/FTM3jURVohHK4Y21WP80mqYgV4SIWiBoZjA41HwbaPMKiyAuPPnEFaBi6azQa7/itRO2PatlZJkFZ1Ln/e0AlIfCZIx50pbXeQrshz8WT25UfMclqmAdxj4XHtgNr1z6FO8HrYw0oTJr8NuGjr/NUm/FM4CDfPcLvSLgu2XjVvR2jqqw4+EDzATmWPV86WPqu3Ft1kj9DNLd5w6N+9qK6rQqEpIGfbh19+rPXMBZL7GhtHiEccKPjNlCGZJNfw18tcOzAUOjwHJLYhr4higoV4s9f2/j1OXz8eknj05jVWwMUvu7b56morSW5LU8lOa7zFOEVbyg5R5XHvxe3/vrgGXiBQhwKD/YGo+FJTEKG6g5E0WamfllvdTrYSgvwiowxdxZ3IAXL763j3X+jXULPOQAdklx5PWNTgxqWG071/yi5qA5Z4ZZhR1QmAVy64PlHaCBlMWbZ2zhiJsr8pwkT3sHBWFLgDKYIeNq08d4bk0nRSPkimaOua13NJ7uGyC6anexvPPm+g79IZSXSm03uM29gJkXnQgA7B7cnOnRMCbEQZrRfiM5+iCsmuOvPKPN/uY9aAhFbFb33K6OVzQ5ox5Qokd06r+Tv2yLAu+rNVpGUsXWTTQFmMPvLCR4+Cc06i5LfT3XH7vrM22kZUpJrbqUKPla764LfI7ud7LKj1zIkb0f8=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: observability
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: infrastructure
spec:
  encryptedData:
    .dockerconfigjson: AgBwqlSJKUy2uYNgNm/g/VDCCMrxpqQ9ZTVVRqfdh60yPu5bcBDIiawKDOHpAx+3cTVUgCnnbuilAf2rpidhMMxj9qO/FyrQ1kYj9g4y5XIdSaCwd45HLUjARfVDnmjaTiJLrc20aPdLtoBgZ1o0EG3cVRhRgpta+XU8bMkFgfT6/Be1L96fkYGkJvbeAOrKFlZQtwX5abNtHHQP+D9k61SgTPy6nC3rHKj1v7sD/lEBBGGEeZIhnW6k1QIlQMxOWCgN9eZTBdOlGP7puwFvbSk60zG5qfk35id2UtDVVbdJbv+CvuKaD7d4IxqgFIXmcZG7bO6xa/FTM3jURVohHK4Y21WP80mqYgV4SIWiBoZjA41HwbaPMKiyAuPPnEFaBi6azQa7/itRO2PatlZJkFZ1Ln/e0AlIfCZIx50pbXeQrshz8WT25UfMclqmAdxj4XHtgNr1z6FO8HrYw0oTJr8NuGjr/NUm/FM4CDfPcLvSLgu2XjVvR2jqqw4+EDzATmWPV86WPqu3Ft1kj9DNLd5w6N+9qK6rQqEpIGfbh19+rPXMBZL7GhtHiEccKPjNlCGZJNfw18tcOzAUOjwHJLYhr4higoV4s9f2/j1OXz8eknj05jVWwMUvu7b56morSW5LU8lOa7zFOEVbyg5R5XHvxe3/vrgGXiBQhwKD/YGo+FJTEKG6g5E0WamfllvdTrYSgvwiowxdxZ3IAXL763j3X+jXULPOQAdklx5PWNTgxqWG071/yi5qA5Z4ZZhR1QmAVy64PlHaCBlMWbZ2zhiJsr8pwkT3sHBWFLgDKYIeNq08d4bk0nRSPkimaOua13NJ7uGyC6anexvPPm+g79IZSXSm03uM29gJkXnQgA7B7cnOnRMCbEQZrRfiM5+iCsmuOvPKPN/uY9aAhFbFb33K6OVzQ5ox5Qokd06r+Tv2yLAu+rNVpGUsXWTTQFmMPvLCR4+Cc06i5LfT3XH7vrM22kZUpJrbqUKPla764LfI7ud7LKj1zIkb0f8=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: infrastructure
    type: kubernetes.io/dockerconfigjson
