apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yml
  - ghcr-secret.yml
  
  - timescaledb/application.yml
  - timescaledb/secret.yml

  - rabbitmq/application.yml
  - rabbitmq/secret.yml

  - mongodb/application.yml
  - mongodb/secret.yml

  - observability/loki-app.yml
  - observability/prometheus-app.yml
  - observability/secret.yml

  - ai-agent/github-runner.yml
  - ai-agent/ollama.yml
  - ai-agent/rbac.yml
  - ai-agent/secret.yml

  - cloudflared/application.yml

  - infrastructure-runner/application.yml
  - infrastructure-runner/rbac.yml
  - infrastructure-runner/secret.yml

  - keycloak/secret.yml

  - backend-api/deployment.yml
  - telemetry-processor/deployment.yml
  - solar-forecast/cronjob.yml
  