apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  
  - timescaledb/deployment.yml
  - timescaledb/secret.yml
  - rabbitmq/deployment.yml
  - rabbitmq/secret.yml
  - mongodb/deployment.yml
  - mongodb/secret.yml

  - ghcr-secret.yml

  - observability/loki-app.yml
  - observability/prometheus-app.yml
  - observability/secret.yml

  - ai-agent/github-runner.yml
  - ai-agent/ollama.yml
  - ai-agent/rbac.yml
  - ai-agent/secret.yml

  - cloudflared/deployment.yml

  - infrastructure-runner/deployment.yml
  - infrastructure-runner/rbac.yml
  - infrastructure-runner/secret.yml

  - keycloak/deployment.yml
  - keycloak/secret.yml

  - backend-api/deployment.yml
  - telemetry-processor/deployment.yml
  - solar-forecast/cronjob.yml
  