apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - timescaledb/deployment.yml
  - timescaledb/configmap.yml
  - timescaledb/secret.yml
  - rabbitmq/deployment.yml
  - rabbitmq/secret.yml
  - mongodb/deployment.yml
  - mongodb/secret.yml

  - ghcr-secret.yml
  
  - backend-api/deployment.yml
  - backend-api/ingress.yml
  - telemetry-processor/deployment.yml
  - solar-forecast/cronjob.yml
  