---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-creds
  namespace: default
spec:
  encryptedData:
    password: AgBEPGQCqUdfzbixRCBjQdcZy1bn7fJK2Bos5TmvQrAxlibumGIpR2Bwxd5Gx/y9AiPxtAsSTUFMEoRsyP5wKKBLcyv0aE32jFBtd+86XwN3MayqAcXqmkGoORXZC/LN2r4Pvhl0X8LxfYEk8tXI/X+vZpfr2qmmNVAPtMgEmzKT2FGcqeIiZc6q9o5yNfWSqkEgY2DmqcbgMsLGM3B+YYuf93dPcpmmdL9XO4AhdWK3lnIrgbwiIt99Vpe1R/vpLf2rV7Vp8dUosOmaYTDWr72FCgJI+C43/6x+6ODQaVOfTGLX6dZ7/Sv6VVXnY0VKBQlJDs9yiN//wbJY1582Rzpr5JGL5MfLqycWQvUkCFaPtT+cF301DM6TRfEIcq4Qk99rpek0LEIdifQ0f+vm41dM9zMir4v1aLHuvDdyvU9HfS6ECYD0BS60A2ZZhyQ0q0n5Tg3I6HOLGUPa5AWTGY6gSdYCFpIpjLrVdRCx1OgXzCtDFjNGNRlozUFYZ069scsjxveftrXT33/p80n+uoQnE9Qz/VtX4bCz24BjbhUB3ngmw6pmczk4SPzfpEw3IEv+OdrSI11G6NqQvW56poZclla7XAzTnkL7Y2f6KRvfxqLicjGhLQLP9K+z9J2b7TxwXVWiSnCftZO+iQyPG3oKQv1WnTURH6bQ80lLQsUFV40W0+PPDslvJyW1NpTj8xvJi+TjYEIeDHsvSBPr
    username: AgCf3FTopMiGORcclCaTrUlkKbX4qG12e76dfoV6bMJ1waQt0q9HpOlEwxAFUetbbtwWopBM+I1Ql90IG4NhmESy4DXVCXwSkP9NYwpeAbNG7DURBUOUMPuTl06httBcNn5w5jnflYtK4LpV+t5tcV1rwI4RaNmSIOIaItvN3SnnjdKvQD6PeoFTjkA9YauT30XWzAjn9Q2swmvXoFDSQ0dR7+FwyLmODhJkn5aTci6DG8h4BVxv4WdveAgbmgemMQYyGZuvuDqWIfRD8wiWDEaf24wrgF9WLdnc1F6c2eDfmvAYQgyJI2ryfaDUM03RthLDyZWpqPIw3TefhZD9L30+Qr6Kv/INM+W0M4gSlEXSd3FuXPZ42RD431/saYnpbpkaink9DQlzbvcoqUPwRle6+uNqo1me/n1MgLjfrvkVqlWlHPaiD1Lz645SKR4Uo9ejl6N/nbgURIqq4+lCj9byKQ6WY2Ueu3lHsV6RKEf4NvirIC+dP1AlOZYqrDYz9OlD/9VLr/SiF7x3jK3b3tCqFX1JG05VFB+0n6yHKet+pUGuVeQl01X0XAxOXTuMJONF5jBmlJjCazMIt3vV5n+bCBGEei8f+btTy+hyidF3aZEWnfNlm0TZSIi82YiUBS12GaK9hx1CjdsFJGjp8GsK3H79eeHN20q5t8SJ1UUw4MT0xFpIxJewCZrJvfgB+mYknU2HkA==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-creds
      namespace: default
