default_user = admin
default_pass = admin

mqtt.default_user = admin
mqtt.default_pass = admin
mqtt.allow_anonymous = true
mqtt.vhost = /
mqtt.exchange = amq.topic

listeners.tcp.default = 5672
mqtt.listeners.tcp.default = 1883