---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: default
spec:
  encryptedData:
    password: AgCIJe1SnyNfRdBs4z4L+dG0VX4plvcL54U22Xghxb19A+xuqgZaceYFwS0FQk71lCAmnHPnx/jM4lXZ0dwUbEyCs7RyWQzEv9QjG5Iqu4RYeXMe7Hnpsxb7LP+8h7xPa9JsqST8mEeHV/UaZXIZM9IONxHT2cAJBhwY0FKaaYeUYkaLTJXs58l6iqFSlJoIFD6fIisNJyi4P3VcTcGfgLnQIDUja9Se0CfM9SxzexCqxm+xI8JBR/BNlPPi9I8MMX52aAvuQa5+xwT4Wh+46WZbD4g9rllK6XX4VBYCb7fMGCVGodNl+cE9Gn7D5j5ZQVVa7GRKUmZe4GxBD+NCPwtU8R8jW3XQmttg966VMeDIMopMkVGx5n0uT8bA1WlyzxN4quWHBvPV7MMzIq++YJTQ5K9jmVTrfz3mib9VpN2JqhNZ2LS3asdw5a63JPJI5VySbAIFErm6U3EPUbKY2R9scxu/xlU/rPKCqPOXxGsOQIBTLDA6dDEovvhabnoUFtvdlFWPnMzCIDOTa99/xRWyQdG20i3aU2h0SEfkkfSLt/GqdavpHwZmYZOoEF6O9r9izNBJZ+HORoA8N6j6kFWa0CSWI1isotyNEl3N8f6Fq6FMZbyrBX27d8jBerr7xOIHOUDiVo0hd6u7bt0PklC1xTL2HTzXYzjU+1PfDcUidnqQFxqQlkYg4Z1X2EHPyU6+6SubNw==
    username: AgAA0Ob0CR1eupHeX7BEvMVAt9W8ySMsd+w2FCwv/cBjLDRTmLfNw8t5HvzipZb8WJbMHXgstWIp9eZAtM9qnN9ix+9gCAylK2DtaPi+pI9etNxbHI5I9kLlQH1niRFOgPXsCE1KpaujRCIYK/hF1d5o3Kg/Oj7EADZYB9rD5mToenpVJDrHFjpauhpVaTt05DzANN9LDFVCRAOIfKloeRVBbVR2qhPd4rX+PtQvwLmwCo0sofcNKsvwnhQCM6LvcI6QSAAeTTsozL3U5BmR7eqpqLJ3xiCr0eU3vQXu9m2Ul+vj0O8XX2XS2hDTrcxeyJnEB3QE8IcKpVhsAO61YFz3nhp8sZMTFM3J71Ha7cqqfWflJb9yb1mL4PlggQt5zCSufc4GF0KsjZy9DpiVVXopXKvjRYpemXiAZFhy4n5qJ5+angMqvnGhxslrlsdmRKYrIOZYAfGpPIAd+sfatrp0wHkl1nEtr10l1Pnu8rJWc/UZ95Sx8IMr3+pLa1gTQROS4//smUJSouXFTC82fR/4woH3n9yJGv5/U8jKTifj/2KmUfKCeiGi28oThY6iZUV6qf5UAqJkdNjYWXLjoxwe/iISa5qo1x2JyKAUMGVcV12mrn0KacQrg5EN2UD0R6jyuEJUdssjhW9qd7mLdr+4fn1HM82XPALrl0yHtOhtrTLgcru1hVvrwZUW2Y3KkAkKYPmkog==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: default
