apiVersion: batch/v1
kind: CronJob
metadata:
  name: solar-forecast
  namespace: default
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: predictor
            image: image_repo/solar-forecast:v1
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: timescale-config
            env:
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: timescale-secrets
                    key: password
          restartPolicy: OnFailure