apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      enableServiceLinks: false
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: backend-api
        image: backend-api:v1
        imagePullPolicy: IfNotPresent
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "timescaledb"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: timescaledb-creds
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-creds
              key: password
        - name: POSTGRES_DB
          value: "default_db"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  selector:
    app: backend-api
  ports:
  - port: 8000
    targetPort: 8000