apiVersion: batch/v1
kind: CronJob
metadata:
  name: solar-forecast
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: solar-forecast
            image: solar-forecast:v1
            imagePullPolicy: IfNotPresent
            env:
            - name: DB_HOST
              value: "timescaledb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "admin"
            - name: DB_NAME
              value: "default_db"
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: "admin"
            - name: MONGO_PASSWORD
              value: "admin"
            - name: MONGO_DB
              value: "default_db"
          restartPolicy: OnFailure