apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: infrastructure
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:1826-d2a87e9b9345
        imagePullPolicy: IfNotPresent
        args:
        - tunnel
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-creds
              key: cloudflared-token