---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-creds
  namespace: observability
spec:
  encryptedData:
    password: AgAiea2VuS4FLNkWVmj2/VkCdbXKDUdMYsnKswgAWW3OIhACIcTlkqjO3p4YC/MTEy6JXv9TRhmzyhugQYSsEWHECN+/c8g1/5Sc/B7U17BKVdadz9uchVDQtUqNbUdYEzgdrCFPiZTz8YTnlINbNhQqcvrL8lTsVGv/tEbWY6H/GhEFd6AJWu7jqj6FI+93y/EQDPpyVxkuq9Ewrl8PO+j76I9b1hFcnADl3PSAU8NmoS9XwJE7tzwXeHOlV8sU8N1OLIgPbB2tJXkNkCeBAg6lvkI0CwQEB9pT/qlUI0KiDQBLOg4q2QqA/k8M6RQaUPjt4Ucpjo4KoNpw4Z8rpbK62e6ylzp/KydJhJuaWMG8cBHjO5JEgvJ3SAmlQrDvPQso/3WxzhvE9L7JTEUDrA5NJC1FkkqqqvFj3C5c2eKa6SV9HvtLU1V0eSweh3QfUeHoV1C3f3TcATVWapiIw0JPrE27Ks4siGGyVbi6ht33tim36G3QVmV2cOcVKRTZjyFdF7VrxKjHMazrTZ4OjE7/g1wpUDzN4Bq3vO3GXYzyekH5DfcmpJw6TzSsAIE4NFD9neR7IWkb4NEVsO3VBs9n6kKMWY9r5/OERg+Jc3Y/AYbZ3O5sOvZE++QrYVRC9r7e0CrBb8UfLNIC7xXdaNRzOrDTN3X+8mWZB+MHam19J2aUB8PB6UY+OnujtMzWpGG5W1UU0Q==
    username: AgBn3Qvlrclm3jmo7/fyBu+VEe3c3+xlLdfYH2fCDoNApshMjvBhidbAZfXyxeTBfiCM/eimKfJ807uTzFnyMxspKa3hXCYmR8dLtJed6wYFDhZoOvMTh8v2jJh0ZGwBZKp6Zqd/xBbWRThXlWRX2qBxChqA29wQyDPlgPJjjXOPbXzofui2yIVCgOoIKpXhUWoKoPYwBQfJFn25ljEXHAxRKfC8TaRncdONkSOTdwkY1wL1iIOoi0wePzxV6qpRmjfyAf4Bqhi/jfrlSXWqA/ANFX+zOyMWmIvEdCCgV7HkNRcn60zj5Kxe/OdIz+cSux82kHf8pDtOuCprEpP4X9nrYdpp1THuUj2DuqEr1X59kRPJISidmFA+8aky0Shth8Ya/6ojDms0/OSWcr/n0CTRlA34m0Xw6TKzIIFP7j91n/9NICCF/4l/WQckO9K+SWtL9LBTN6MRxA6lMvHq5SJN7yIrV2L8sBHLHZWdIUw4z9RUQTYkm48+IIxkMnVgN2iDtv5oxcFHYadAQImUj9kQHd+KpAhVrXqlIFDgsuTDr10mnxh+rQCwyNqESl2P8CcpfCi3Tm78WT2zmE8GQNGe1xIdPRfb9Cuehsr5ljcbilVKYFmRBIShgDpSyfZJPokdh5rL0/Q9JHFc+44+4SEXF/UQ/9/y7iybPg7qzdOcxHAT7QcmYZqLcbu+aY09NV+EYFzBxA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-creds
      namespace: observability
