---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBjVYvGVOlsoMJHtlqEd5gjNMRDogsPoyh3ZyMxlfust/0eMTMnTE6ZS+VASH3q3388iSxDijUIzH3+Rhthwi/G5ljpHlPD9X2ZUaORlN+vb28wsVIXf+TLj8D7a1jXRruBDo2N3kACJyZILt7nEz9ABgkPcp7ogPSF58+eCuQRNWBkRQtEzsu1UkgbwcRyLTnhJ2a9D4tp8u0/Zn3nmFYsT+U/0+ne+FyC4LRxUisk04vXIPvlflE7V77YV33aOemLMMQkBHUVjZcu2GBIqgW0hKkhuhvuc7emCh08AApHQ8fe7dTdOWZ7JZfKcpMzpjZg59Mn5hsM1upilRC/ZoKomQYrR5O1NtpVWOoV5R6ci0JXvSS4SrtU/slvU2BAtYKRUStQjEPvG6m1vnhUYWOxekx3LI26XmTRpSBXTzXlEVLEpZA66Yw0J1xPzBOyYQLgCSlKzkPO9BFOWWgoIo5aOKfIDpdCCvOLqyEOoD4PBeJTgLf1xpt0hQi2QDYjamECgI9l/iTGLnwdpdPD4Or1gYJZgEfubwsI6yY6+Q+XyP+fOwBYJc8t3XGmCO8fDb1uR+PDJrNZknhd7SMhUfwi9006OZW/2X2cj2HBrgbDT3Ub/xtxigz7MbmIv8nUmCtqdMEXGUi+FklnvbNvrJQRj27ykI5A2z9V6idu8yc4v1SXvcKjYBHX+iH6cuqORytHGVB9StNuXn4E23SsOthkfmNCTqfX6KpRtnuvqYifNWMMaWg0QJG7BtT3bc2EMT5dvjbF2Rs1GvxAmG02f816QACrV0oF5qfeXSJBf/c/jJc5TsqUWx0eBluQp4GfdYiuJLLpCoae22k/KsIkRy2D9v9AuSz9SLZan1emZynVZOdQSBd0hU5Ct5ug4Zfpm8gyDpXN8FNxwIr0jPIVNHwAcPk1lc4QuCrcHWzvrVw2M7DpZ7xKLvV2jrSHCX82Qip2zYnIHZE=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: ai-agent
spec:
  encryptedData:
    .dockerconfigjson: AgCJNF8aX3nlCC4MR6Gt9bbvLqlpVuTZVlvIhgkEGisUGaYiGGMApcdmnO13Ol2KHGSONQpNq9+pGONx2XlbkHd8xbFuZZPh/MfgbowBpMnfi0p13sgI4FVTOF4Pg+L9Bopg5bRHb3LGI6wjN9yKgmyQuunXJvRH63R+BZScYAcx4aeKl54iIxzPOkcICBZAjx4UPO7iLLa4t3kfFNLb+n3Lp9XacTOzBa7S4Wg0P9gvEuaHRFdq2D68F9W7XyuQnkMCAgRgntc34U7n3kO/UpKgvw1tjIBRTE8qS4aTYDLcOTq4+FgVXJCG/PXtyySXfrF7ANgwSuMjfRT0q5tYpZCcbfWb2dusfnHRXNSOoGKHU1bFkFp2a9WEqtPwf6wKEiNwHadRivQYedQuGMjwXKa55qeE0+UQmtRWrrIndQtiLBzKSlUb2RZfYYBGMwVSvkaVTcngXYmVu9umF7Dw4NxNS7kPyyDPHdgNZtaNl34/sNe7M89BLxT+udGyrjt329qqbvqeYA935ddFdhs4Ke/ZEz9yURYke1C6KrTuAY6JhXwocgPnpmaRI7+UHlX2edDBx4AHe4Gr3ZovBa8Hqmd0S+g0fyRO0njUuthjiUcxGwAWB6TryLkJsGpHh7oGXyl48sCbndjiPUmovF7Td6jbTz2J6z3aq+A/y+HyVBdYTHbO8zBJZJBQKWNQ+fNMxcAXGgZVY02StXcy6pKWDz2ddUy1qqawVC3M5nsDX9uarM4j1C9Nc2CVB/XohfzInFQMf+ivAL26ZQe+dmiSoFDmJBJJG73PAq4ECd/SU39FYb6rAml3xDV0nLt/QTGcYJUdGNOGqfXdIKJwO++VqGYxSZRTqktbG9GJPCcL6Xu83+hV7G/WWr2agV+0zYthu8TcUhFAGEilE/Pp6k+raGd99H8sOWm5RfMbTGk2JiUlUOvFc9Y2YLVs9Jhmn+LjftyB/XRJJSc=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: ai-agent
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: infrastructure
spec:
  encryptedData:
    .dockerconfigjson: AgBr94RBltjwM+Qo3zY1CQo/ggXDOAAn3sMPwJpgTcdL9xVgdifPusSpcBXn+dOqO6w8/AAj8tXKJLsOjEZECUgLcS2WgD1LRzTotvuAojcSJAViFXxtv2NQVW8bTjkza9SN65VmIDD3JtrRs+H3dC3eYZRs4NPFg4VR+7Dk+Dldyz/vDzuR/RF6hxTfg/wRe8Y/VTedFSFzLdCqlDngWZHkxKm+bNCGh8pMgvk8pecfG8kuY+R4VXH/WRu4c8cASP/+7KzTD3iu1X/+8EPqxvgUVlY72xyKFvHW4rBEMqzOOEIiNB83hv4L4LB6r6yKWhZd89AX4qoml6MyDTGAN/Il24kA5Py7qiON/U4oCjU+IruVAkHoYD5LaZZLVI7BjEgQZIo+427uVXAeW5qjHCkmmX6RgzJMVKuMhco3ZGYVApruWDr7eCGtKnKssPB4yXKqazGv4O4nN/1bNcBkrVZEsDbdNWIcdjJDd4UrSFS0QvaFotgnQnpuHiM1yzPazHHLtLO3QYOuiAyvR46WDy1fA7PagMU0Iv8XaVKaElh2XKIEEekhTlckZjkcN9bxFbcDpKX1eJOUdOcjxJ4grusI5dy9rIxu3ux2czZhYNn6rMeyFISAWBFI6GSV4C0rlR2Rf6/HAS+NavIoSRpr46xw6PO/Qw0G4GkbYd9gNQum+EBXhcADTbwmZjvWbLhP+uLgmYufCvul8ECEH4Ml4jLP4yBgs3QqrrmvtirS8+wfhIiaBgbYvfVS5InVBCJ0/0Yy95MWvY8NtyVUyLZXgLCp2j1DoihhBzNRCHbiOGbw0zwGAK4w8L2ut6Bkv4FpdkmsDxmjPL8Wlk7szfE0nOkJQQmVWtiKZZ9RMmWeXBlTVGVM1Fky4f7QMcb5JgUP7/VA4qb0kUq5KyfVPpwnJNBa41n1pCkKXLxbTjOt66Dd51rVbPTqTo6CMawz9CSVP6NP/B+HUcA=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: infrastructure
    type: kubernetes.io/dockerconfigjson
