---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-secret
spec:
  encryptedData:
    .dockerconfigjson: AgAHUEDaatODI6XlpImtbsMs9LCRB+nzPR5L6DhigpnWrZIdhcf98EBSR+/zu9kHFyxKZBS0wPM4V70foInAHleIwelQaOU45HMfFg6+0MsE/j9p4bHo94tWyjuUA0NCYDB4X7i+cmO1x+W3G6yvcVz5o0JD3KAdcKtkK4hU/rp7um2dBT3kkOSbcLt8PPoV8Uv/F8MI7LZmltx37LnTO/cJ1FwFQae/RLM7LPVOWzigCj4YrH+vyQYZ/KIrreTwJhV3MR1sgmtaTiLzhYHn63H16GhtWEahLuhpRQwQaV7JQHhX3T5MIlmQ79OJ5if2sK/px//5Cjf68RHM1bSVSZW2+Z3CFYtHROK4UhBry/BfX7+/9qYH9CFeM8EuN1c4dT3D2lWuBahOAyPJhpLVIiXg+FW+OwdezZOYgWbc4phPZ2YTwFDuQ5am/xQKlWUxNu+twReuJxuYgD6b7LlB4C/898lPWdRoUlp03TFPgLni6hbtiYdeVWLbPLz9lglikQAb9+Zapy9vNfFky7239PzYTrrKioJJTbPhuiV1WEP/w4lI3BriDoDhTyC6sgYCIY+l+SX7kSpqnPF9C3FAzJ6EJCQbCKe/baHOzM2ZYdzwILKAC3i1RR/TsaTC1dV3f/1ycZ5PGwfcWj/7ntPy9EQvarT3Q5zXDcfrhc0aTBQI26YCu8cUgBvNXTFsIM2m8xP0TyQQqXWzKP+lwwopxCcjtrDb9Yt9BjQZTHDNkO9QPalDhdqCOL3fjxA1SV3s9b3fLkbYUQZZcB6Kxr+zYoBKoJVv/seirFJ9NiCFsYXMK0b4Wbu6VCKETVk4MM3aeTP0QHrE8/sby+5iw/nMhU/ftOHbxRU3M4nQ+i5UA9ercwQ7y7FbosEqeB44eCjkCMksIt+lHRWwHw1Xx6ybozGYsbPf/VgjgYNh8W4wYFrSs094j8UwsahvX86pAYoqxHJKsCZumFU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-secret
    type: kubernetes.io/dockerconfigjson
