---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-key-secret
  namespace: default
spec:
  encryptedData:
    key: AgCgw30mMbYPCgnRBk0CsPJO9inEU5QWbya/OcoYVTvMewEJq4ezGYrC7ZRE7KUCXHzwz4sKCsJrtIE2e50dvig2L+tX4m+3u2HLe4+ajnEXgY32xKj79QZfpsW62Caw1nf7yEDcbckei7GJ69xsMsGYwo/NqVbyW/9TqfewSEvNqemyhtdKGrtL8JDlfrDD79Vc+efwONMhHRSb8KhYtZu0jmMeJTnO8QjFBsmsolT3NUF3B8XVPaWP6KoOPQgvRo3/PQTp4Errdk1UgzHrVTYZ9/npUQ0FMfp+xr2W/rsLqQ53iKHt4srzD5xoWlYrXGHFsF+ACeusX2gpwbnAkiH+f6Qrsjn+zfU9Wh5froHNqeJGUUjqBBBHHoyiMRA2lQQkwNsKzDcN0/lokPboSYMyEvbTZUXZfhJClrer5FltBVi0so3YoaFSYghI6JuMLgKkAyb3G3wctxXGbVFPduSZ21vFJmQ0QJFMkkuOxtBICMDImjByusyU9Qns1IZzGQHCt6V9okXaswfkmHkBd8yE7QHsgJPLN/7Ly3wnLIGFnm2LFu0IWOW4Jv9v7LTNP1ol3c51xELtlmODlWp2W0O6uc1Av8iU1U6NX2DpysLrlVZLzAlqowE8p4tgeGC0w994MI1cMTqsdyy0q6zUAwt+1TnIlIZ/VDXFU5QdZq+QevEv9JPt776OCLR/g2i5wq/zzsbbxjBV/yh1ApOhwi8+Sns5BMtcLuNO+XhL5yCxLg==
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-key-secret
      namespace: default
