---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-creds
  namespace: default
spec:
  encryptedData:
    password: AgB5s2AtpbtnhhPdEtBPXzf2Mb4c3pK3rdTUTxwytZnkT0prslLs5kmcR5bifMg+xzwsLOnpE7iBrCy+y8vHyptJtJ/LvuA5gDQ+QOiEJeTWMIwqyeyk02Hs0xQpUWeT4LQJN7rFmYHY/cH8lfEs188dvdQENF3wn5zGXv5SBxNO4HXJpV6JULClPf9sXX8Z/DwUStbRcRn/xElaroQIa5PDVKUwMc0SW4Chdrc66+Z4W6KPqQvvr2atu5hz/s6OJwrRwfFSzDvtTW2j8FfTfnBlMdZPxK3K4OtGP+kINmVPcUCOBFSOlAtWmF7zMlgI0gwaD501qGh4yR/SAUGtMpA72nTuhn03zGtFt4VQD8Vdc2RIo/IuOctdlBCjopOLUjKs9yQZ8NcLEpipJkrye6vWdG5tXcBpTW9lVw9ZIiVQQlw5heSm+tnEBdPbFuHs2sLWijLf8enx8iBM4SFHT4MSX03xawUpUKEcfGcw3pygK5pUremsVbHfw8Nr1lttVWLERfIfvl5IiBg4AcEhYJ3Vv0JQm+7PfS1vD59TWjzJ9QUWStIvAJLIlPRxKRfPOeMLYNWVDDDfD4NfVFmHw9ATrAIrpR3Y25Iq1boQ4UNOpeCJb4bFnllpM1T0Fgt+OycI++7dIViq0hfVO4mCeTu9RLtFjsfyctcEC3ccexApTW8NnLfTZ97UeqCQdO7OPD0xWb0Urw==
    username: AgBgTqYZhnJXdXkADgYX8sXf8bFgyUu0lw6PyaSLb+T0VZGS4/7BOfEeW2edVx/nTWFu5HfabVIr8tKq2Y3JgpXwL46l2eTo9stvqP0NsngrywsSUGJ53QazHekt6g3OQUYHNLPkD2pwOyCy/JPjI9Iu58c7/QEXcc/ZKF8OJ2yz0WzHm1UXKvaAjRgI9kMrYyLivYE4KvA2fPVlofA/Fr9pL4n90jaCuT9HMRF8xWDeHWVzdEt78Mjprf29tern8Y+qM+7FGaNRepeXq/j8E9KMpu7Cv2SAOI0mWemazc29nRzLzSygGPU32sACP1AavHywzc1fq4Si2eoS4rq0/uZxKn9yKFjKXEMWG2keel+ZSwDquyOtaXBcowj3cYC9+M92HXQfUC4Vn/tXf+lYxSEhrxMcfu0tvLKLK562I4pEwXd/wALr7lmNuSqCabjSwJl3I/Y+1kpupojOQT+X2nnAvhVvMMBrU1wYmTIylrKAil/aw5eRqrn08LMcrUWHjRlfcSKyLLkb6xuABahc/6AkDV3OgDGoSEXvZD/9V/5IhpBZ5OI21nKo4S41YkX6hxhDd0vIYDuAsvMA07Vj7SE2xkM8AcBDuC7qQD+vfuxdD3OwiGCL3ubOf13yAs4YeniKwVWcwoMQdCq4Vv0I9i4Vqoe3bBuTZ4ucf/3AOZnrB5J4cRWkg2jiZDRZHxwSwUysuGXKvQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-creds
      namespace: default
