name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'services/**'
      - 'cron-jobs/**'
      - '.github/workflows/build-general-images.yml'

permissions:
  packages: write
  contents: write

concurrency:
  group: build-docker-images-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Filter changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend-api: 'services/backend-api/**'
            telemetry-processor: 'services/telemetry-processor/**'
            esp32-simulator: 'services/esp32-simulator/**'
            solar-forecast: 'cron-jobs/solar-forecast/**'
            downtime-checking: 'cron-jobs/downtime-checking/**'

  build-and-push:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.services != '[]' && needs.detect-changes.outputs.services != '' }}
    runs-on: k8s-infra-runner
    
    strategy:
      matrix:
        name: ${{ fromJSON(needs.detect-changes.outputs.services) }}
      fail-fast: false

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Context Path
        id: set-path
        run: |
          if [ -d "services/${{ matrix.name }}" ]; then
            echo "CONTEXT_PATH=services/${{ matrix.name }}" >> $GITHUB_ENV
          else
            echo "CONTEXT_PATH=cron-jobs/${{ matrix.name }}" >> $GITHUB_ENV
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/klaudiuszsoltysik/solartracker/${{ matrix.name }}
          tags: |
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.CONTEXT_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Kustomization and Push
        working-directory: ./infrastructure/k8s/dev
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          MAX_RETRIES=5
          for ((i=1; i<=MAX_RETRIES; i++)); do
            git fetch origin master
            git reset --hard origin/master

            kustomize edit set image ${{ matrix.name }}=ghcr.io/klaudiuszsoltysik/solartracker/${{ matrix.name }}:sha-${GITHUB_SHA::7}
            
            awk 'NF' kustomization.yml > tmp.yml && mv tmp.yml kustomization.yml

            git add kustomization.yml
            if git diff --staged --quiet; then
               exit 0
            fi
            
            git commit -m "chore: update ${{ matrix.name }} image tag to sha-${GITHUB_SHA::7} [skip ci]"
            
            if git push origin master; then
              exit 0
            else
              sleep $((RANDOM % 5 + 1))
            fi
          done
          
          exit 1