apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-processor
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: telemetry-processor
  template:
    metadata:
      labels:
        app: telemetry-processor
    spec:
      enableServiceLinks: false
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: telemetry-processor
        image: telemetry-processor:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-creds
              key: password
        - name: POSTGRES_HOST
          value: "timescaledb"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: timescaledb-creds
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-creds
              key: password
        - name: POSTGRES_DB
          value: "default_db"